trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm i -g vsce
      npm i
      vsce package
      vsce publish -p $(VS_TOKEN)
    displayName: build and publish package
